<?xml version="1.0"?>
	<robot name="weed" xmlns:xacro="http://ros.org/wiki/xacro">

	<link name="base_footprint"/>

	<joint name="base_joint" type="fixed">
		<parent link="base_footprint"/>
		<child link="base_link" />
		<origin xyz="0 0 0.8" rpy="0 0 0"/>
	</joint>

	<link name="base_link">
    <inertial>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<mass value="30" />
		</inertial>
  </link>

	<!-- #################### LEGS #################### -->

	<joint name="front_left_joint" type="fixed">
		<parent link="base_link"/>
		<child link="front_left" />
		<origin xyz="0.4 0.65 0" rpy="0 0 0"/>
	</joint>

	<link name="front_left">
		<inertial>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<mass value="1" />
			<inertia ixx="0" ixy="0.0" ixz="0.0"
					iyy="0" iyz="0.0"
					izz="0" />
		</inertial>
		<visual>    
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size = "0.05 0.05 0.5"/>
			</geometry>
			<material name="">
				<color rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size = "0.05 0.05 0.5"/>
			</geometry>
		</collision>
	</link>

	<joint name="front_right_joint" type="fixed">
		<parent link="base_link"/>
		<child link="front_right" />
		<origin xyz="0.4 -0.65 0" rpy="0 0 0"/>
	</joint>

	<link name="front_right">
		<inertial>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<mass value="1" />
			<inertia ixx="0" ixy="0.0" ixz="0.0"
					iyy="0" iyz="0.0"
					izz="0" />
		</inertial>
		<visual>    
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size = "0.05 0.05 0.5"/>
			</geometry>
			<material name="">
				<color rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size = "0.05 0.05 0.5"/>
			</geometry>
		</collision>
	</link>

	<joint name="back_left_joint" type="fixed">
		<parent link="base_link"/>
		<child link="back_left" />
		<origin xyz="-0.4 0.65 0" rpy="0 0 0"/>
	</joint>

	<link name="back_left">
		<inertial>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<mass value="1" />
			<inertia ixx="0" ixy="0.0" ixz="0.0"
					iyy="0" iyz="0.0"
					izz="0" />
		</inertial>
		<visual>    
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size = "0.05 0.05 0.5"/>
			</geometry>
			<material name="">
				<color rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size = "0.05 0.05 0.4"/>
			</geometry>
		</collision>
	</link>

	<joint name="back_right_joint" type="fixed">
		<parent link="base_link"/>
		<child link="back_right" />
		<origin xyz="-0.4 -0.65 0" rpy="0 0 0"/>
	</joint>

	<link name="back_right">
		<inertial>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<mass value="1" />
			<inertia ixx="0" ixy="0.0" ixz="0.0"
					iyy="0" iyz="0.0"
					izz="0" />
		</inertial>
		<visual>    
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size = "0.05 0.05 0.5"/>
			</geometry>
			<material name="">
				<color rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size = "0.05 0.05 0.4"/>
			</geometry>
		</collision>
	</link>


	<!-- #################### TOP #################### -->

	<joint name="top_front_joint" type="fixed">
		<parent link="base_link"/>
		<child link="top_front" />
		<origin xyz="0.4 0 0.25" rpy="0 0 0"/>
	</joint>

	<link name="top_front">
		<inertial>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<mass value="1" />
			<inertia ixx="0" ixy="0.0" ixz="0.0"
					iyy="0" iyz="0.0"
					izz="0" />
		</inertial>
		<visual>    
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size = "0.05 1.3 0.05"/>
			</geometry>
			<material name="">
				<color rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size = "0.05 1.3 0.05"/>
			</geometry>
		</collision>
	</link>

	<joint name="top_back_joint" type="fixed">
		<parent link="base_link"/>
		<child link="top_back" />
		<origin xyz="-0.4 0 0.25" rpy="0 0 0"/>
	</joint>

	<link name="top_back">
		<inertial>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<mass value="1" />
			<inertia ixx="0" ixy="0.0" ixz="0.0"
					iyy="0" iyz="0.0"
					izz="0" />
		</inertial>
		<visual>    
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size = "0.05 1.3 0.05"/>
			</geometry>
			<material name="">
				<color rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size = "0.05 1.3 0.05"/>
			</geometry>
		</collision>
	</link>

	<joint name="top_left_joint" type="fixed">
		<parent link="base_link"/>
		<child link="top_left" />
		<origin xyz="0 0.65 0.25" rpy="0 0 0"/>
	</joint>

	<link name="top_left">
		<inertial>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<mass value="1" />
			<inertia ixx="0" ixy="0.0" ixz="0.0"
					iyy="0" iyz="0.0"
					izz="0" />
		</inertial>
		<visual>    
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size = "0.8 0.05 0.05"/>
			</geometry>
			<material name="">
				<color rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size = "0.8 0.05 0.05"/>
			</geometry>
		</collision>
	</link>

	<joint name="top_right_joint" type="fixed">
		<parent link="base_link"/>
		<child link="top_right" />
		<origin xyz="0 -0.65 0.25" rpy="0 0 0"/>
	</joint>

	<link name="top_right">
		<inertial>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<mass value="1" />
			<inertia ixx="0" ixy="0.0" ixz="0.0"
					iyy="0" iyz="0.0"
					izz="0" />
		</inertial>
		<visual>    
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size = "0.8 0.05 0.05"/>
			</geometry>
			<material name="">
				<color rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size = "0.8 0.05 0.05"/>
			</geometry>
		</collision>
	</link>

	<!-- TEKERLEK -->
  <link
    name="front_w_l">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="3.630032967311711" />
      <inertia
        ixx="0.00669221232999861"
        ixy="1.46876065216874E-06"
        ixz="-1.83677052642238E-07"
        iyy="0.00381017219621702"
        iyz="2.02228538609624E-07"
        izz="0.00380710944075326" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
     <geometry>
       <cylinder radius="0.21" length="0.105"/>
     </geometry>
      <material
        name="">
        <color
          rgba="0.501960784313725 0.501960784313725 0.501960784313725 1" />
      </material>
    </visual>
    <collision>
      <surface>
        <friction>
          <ode><mu>100000.0</mu><mu2>100000.0</mu2></ode>
        </friction>
      </surface>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
     <geometry>
       <cylinder radius="0.21" length="0.105"/>
     </geometry>
    </collision>
  </link>
  <joint
    name="front_wl_j"
    type="continuous">
    <origin
      xyz="0.4 0.65 -0.54"
      rpy="1.57 0 0" />
    <parent
      link="base_link" />
    <child
      link="front_w_l" />
    <axis
      xyz="0 0 1" />
  </joint>
  <link
    name="front_w_r">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="3.630032967311706" />
      <inertia
        ixx="0.0066922123299986"
        ixy="1.4687606367534E-06"
        ixz="-1.83677063980871E-07"
        iyy="0.00381016787088096"
        iyz="2.02228538641145E-07"
        izz="0.00380710511541725" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
     <geometry>
       <cylinder radius="0.21" length="0.105"/>
     </geometry>
      <material
        name="">
        <color
          rgba="0.501960784313725 0.501960784313725 0.501960784313725 1" />
      </material>
    </visual>
    <collision>
      <surface>
        <friction>
          <ode><mu>100000.0</mu><mu2>100000.0</mu2></ode>
        </friction>
      </surface>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
     <geometry>
       <cylinder radius="0.21" length="0.105"/>
     </geometry>
    </collision>
  </link>
  <joint
    name="front_wr_j"
    type="continuous">
    <origin
      xyz="0.4 -0.65 -0.54"
      rpy="1.57 0 0" />
    <parent
      link="base_link" />
    <child
      link="front_w_r" />
    <axis
      xyz="0 0 1" />
  </joint>
  <link
    name="back_c_l">
    <inertial>
      <origin
        xyz="0.0408020089137942 -2.20027751224317E-06 -0.0753064138736016"
        rpy="0 0 0" />
      <mass
        value="3" />
      <inertia
        ixx="0.0119429751240832"
        ixy="1.51346058960582E-07"
        ixz="0.0047086697609114"
        iyy="0.012719613396601"
        iyz="-3.20565703090961E-07"
        izz="0.00449043316235224" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
     <geometry>
       <box size = "0.01 0.01 0.01"/>
     </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <surface>
        <friction>
          <ode><mu>100000.0</mu><mu2>100000.0</mu2></ode>
        </friction>
      </surface>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
     <geometry>
       <box size = "0.01 0.01 0.01"/>
     </geometry>
    </collision>
  </link>
  <joint
    name="back_cl_j"
    type="continuous">
    <origin
      xyz="-0.4 0.65 -0.62"
      rpy="0 -0 0" />
    <parent
      link="base_link" />
    <child
      link="back_c_l" />
    <axis
      xyz="0 0 1" />
    <limit effort="10000" velocity="1000"/>
    <!-- <joint_properties damping="1.0" friction="1.0" /> -->
  </joint>
  <link
    name="back_w_l">
    <inertial>
      <origin
        xyz="-0.000406180079597973 -6.75068276938251E-05 1.52646951747659E-05"
        rpy="0 0 0" />
      <mass
        value="0.630032967311717" />
      <inertia
        ixx="0.00669221232999866"
        ixy="1.46876065217403E-06"
        ixz="-1.83677052642392E-07"
        iyy="0.00381017219621705"
        iyz="2.02228538599299E-07"
        izz="0.00380710944075334" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
     <geometry>
       <cylinder radius="0.13" length="0.078"/>
     </geometry>
      <material
        name="">
        <color
          rgba="0.501960784313725 0.501960784313725 0.501960784313725 1" />
      </material>
    </visual>
    <collision>
      <surface>
        <friction>
          <ode><mu>100000.0</mu><mu2>100000.0</mu2></ode>
        </friction>
      </surface>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
     <geometry>
       <cylinder radius="0.13" length="0.078"/>
     </geometry>
    </collision>
  </link>
  <joint
    name="back_wl_j"
    type="continuous">
    <origin
      xyz="0.079407 0 0"
      rpy="1.57 0 0" />
    <parent
      link="back_c_l" />
    <child
      link="back_w_l" />
    <axis
      xyz="0 0 1" />
  </joint>
  <link
    name="back_c_r">
    <inertial>
      <origin
        xyz="-0.0408020085623402 2.19978087612205E-06 -0.0753064146672595"
        rpy="0 0 0" />
      <mass
        value="3" />
      <inertia
        ixx="0.0119429749924109"
        ixy="1.51328903334174E-07"
        ixz="-0.00470866980430646"
        iyy="0.0127196133801171"
        iyz="3.20626513970711E-07"
        izz="0.00449043322343492" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
     <geometry>
       <box size = "0.01 0.01 0.01"/>
     </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <surface>
        <friction>
          <ode><mu>100000.0</mu><mu2>100000.0</mu2></ode>
        </friction>
      </surface>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
     <geometry>
       <box size = "0.01 0.01 0.01"/>
     </geometry>
    </collision>
  </link>
  <joint
    name="back_cr_j"
    type="continuous">
    <origin
      xyz="-0.4 -0.65 -0.62"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="back_c_r" />
    <axis
      xyz="0 0 1" />
    <limit effort="10000" velocity="1000"/>
    <!-- <joint_properties damping="1.0" friction="1.0" /> -->
  </joint>
  <link
    name="back_w_r">
    <inertial>
      <origin
        xyz="-0.000406180073682316 -6.75068276933533E-05 1.52646951745439E-05"
        rpy="0 0 0" />
      <mass
        value="0.630032967311691" />
      <inertia
        ixx="0.0066922123299985"
        ixy="1.46876064431743E-06"
        ixz="-1.83677052786695E-07"
        iyy="0.00381017423444503"
        iyz="2.0222853863883E-07"
        izz="0.0038071114789812" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
     <geometry>
       <cylinder radius="0.13" length="0.078"/>
     </geometry>
      <material
        name="">
        <color
          rgba="0.501960784313725 0.501960784313725 0.501960784313725 1" />
      </material>
    </visual>
    <collision>
      <surface>
        <friction>
          <ode><mu>100000.0</mu><mu2>100000.0</mu2></ode>
        </friction>
      </surface>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
     <geometry>
       <cylinder radius="0.13" length="0.078"/>
     </geometry>
    </collision>
  </link>
  <joint
    name="back_wr_j"
    type="continuous">
    <origin
      xyz="-0.079407 0 0"
      rpy="1.57 0 0" />
    <parent
      link="back_c_r" />
    <child
      link="back_w_r" />
    <axis
      xyz="0 0 1" />
  </joint>

  <gazebo reference="front_left">
    <material>Gazebo/Red</material>
  </gazebo>
  <gazebo reference="front_right">
    <material>Gazebo/Red</material>
  </gazebo>
  <gazebo reference="back_left">
    <material>Gazebo/Red</material>
  </gazebo>
  <gazebo reference="back_right">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="top_front">
    <material>Gazebo/Red</material>
  </gazebo>
  <gazebo reference="top_back">
    <material>Gazebo/Red</material>
  </gazebo>
  <gazebo reference="top_left">
    <material>Gazebo/Red</material>
  </gazebo>
  <gazebo reference="top_right">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="front_w_l">
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="front_w_r">
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="back_w_l">
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="back_w_r">
    <material>Gazebo/Black</material>
  </gazebo>

<gazebo>
          <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">

      <update_rate>30</update_rate>

      <!-- wheels -->
      <left_joint>front_wl_j</left_joint>
      <right_joint>front_wr_j</right_joint>

      <!-- kinematics -->
      <wheel_separation>1.4</wheel_separation>
      <wheel_diameter>0.42</wheel_diameter>

      <!-- limits -->
      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>

      <command_topic>cmd_vel</command_topic>

      <!-- output -->
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>false</publish_wheel_tf>

      <odometry_topic>odom</odometry_topic>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_footprint</robot_base_frame>

    </plugin>
    
    <plugin name="turtlebot3_joint_state" filename="libgazebo_ros_joint_state_publisher.so">
      <ros>
        <!-- <namespace>/tb3</namespace> -->
        <remapping>~/out:=joint_states</remapping>
      </ros>
      <update_rate>30</update_rate>
      <joint_name>front_wl_j</joint_name>
      <joint_name>front_wr_j</joint_name>
      
      <joint_name>back_wl_j</joint_name>
      <joint_name>back_wr_j</joint_name>
      
      <joint_name>back_cl_j</joint_name>
      <joint_name>back_cr_j</joint_name>
    </plugin> 
  </gazebo>

<!-- ########################### CAMERA ############################# -->
  <joint name="camera_joint" type="fixed">
    <origin xyz="0.4 0 -0.25" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="camera_link"/>
  </joint>

  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <box size="0.015 0.030 0.027"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <box size="0.015 0.030 0.027"/>
      </geometry>
    </collision>
  </link>

  <joint name="camera_rgb_joint" type="fixed">
    <origin xyz="0.003 0.011 0.009" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_rgb_frame"/>
  </joint>
  <link name="camera_rgb_frame"/>

  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_rgb_frame"/>
    <child link="camera_rgb_optical_frame"/>
  </joint>
  <link name="camera_rgb_optical_frame"/>

  <gazebo reference="camera_link">
      <sensor type="camera" name="camera">
          <update_rate>30.0</update_rate>
          <camera name="head">
              <horizontal_fov>1.3962634</horizontal_fov>
              <image>
                  <width>800</width>
                  <height>600</height>
                  <format>R8G8B8</format>
              </image>
              <clip>
                  <near>0.02</near>
                  <far>300</far>
              </clip>
              <noise>
                  <type>gaussian</type>
                  <mean>0.0</mean>
                  <stddev>0.007</stddev>
              </noise>
          </camera>
          <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
              <alwaysOn>true</alwaysOn>
              <updateRate>30.0</updateRate>
              <cameraName>iRobot/camera</cameraName>
              <imageTopicName>image_raw</imageTopicName>
              <cameraInfoTopicName>camera_info</cameraInfoTopicName>
              <frameName>camera_link</frameName>
              <hackBaseline>0.07</hackBaseline>
              <distortionK1>0.0</distortionK1>
              <distortionK2>0.0</distortionK2>
              <distortionK3>0.0</distortionK3>
              <distortionT1>0.0</distortionT1>
              <distortionT2>0.0</distortionT2>
          </plugin>
      </sensor>
</gazebo>


    <xacro:property name="M_PI" value="3.1415926535897931" />
  
    <!-- The following values are approximate, and the camera node
     publishing TF values with actual calibrated camera extrinsic values -->
    <xacro:property name="d435_cam_depth_to_left_ir_offset" value="0.0"/>
    <xacro:property name="d435_cam_depth_to_right_ir_offset" value="-0.050"/>
    <xacro:property name="d435_cam_depth_to_color_offset" value="0.015"/>
  
    <!-- The following values model the aluminum peripherial case for the
    D435 camera, with the camera joint represented by the actual 
    peripherial camera tripod mount -->
    <xacro:property name="d435_cam_width" value="0.090"/>
    <xacro:property name="d435_cam_height" value="0.025"/>
    <xacro:property name="d435_cam_depth" value="0.02505"/>
    <xacro:property name="d435_cam_mount_from_center_offset" value="0.0149"/>
  
    <!-- The following offset is relative the the physical D435 camera peripherial
    camera tripod mount -->
    <xacro:property name="d435_cam_depth_px" value="${d435_cam_mount_from_center_offset}"/>
    <xacro:property name="d435_cam_depth_py" value="0.0175"/>
    <xacro:property name="d435_cam_depth_pz" value="${d435_cam_height/2}"/>

    <material name="realsense_camera_aluminum">
    <color rgba="0.5 0.5 0.5 1"/>
    </material>


    <!-- camera body, with origin at bottom screw mount -->
    <joint name="realsense_camera_joint" type="fixed">
      <origin xyz="0.4 0 0.25" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="realsense_camera_bottom_screw_frame" />
    </joint>
    <link name="realsense_camera_bottom_screw_frame"/>

    <joint name="realsense_camera_link_joint" type="fixed">
      <origin xyz="0 ${d435_cam_depth_py} ${d435_cam_depth_pz}" rpy="0 0 0"/>
      <parent link="realsense_camera_bottom_screw_frame"/>
      <child link="realsense_camera_link" />
    </joint>

    <link name="realsense_camera_link">
      <visual>
      <origin xyz="${d435_cam_mount_from_center_offset} ${-d435_cam_depth_py} 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
        <material name="realsense_camera_aluminum"/>
      </visual>
      <collision>
        <origin xyz="0 ${-d435_cam_depth_py} 0" rpy="0 0 0"/>
        <geometry>
        <box size="${d435_cam_depth} ${d435_cam_width} ${d435_cam_height}"/>
        </geometry>
      </collision>
      <inertial>
        <!-- The following are not reliable values, and should not be used for modeling -->
        <mass value="0.564" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />
      </inertial>
    </link>
   
    <!-- camera depth joints and links -->
    <joint name="realsense_camera_depth_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="realsense_camera_link"/>
      <child link="realsense_camera_depth_frame" />
    </joint>
    <link name="realsense_camera_depth_frame"/>

    <joint name="realsense_camera_depth_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="realsense_camera_depth_frame" />
      <child link="realsense_camera_depth_optical_frame" />
    </joint>
    <link name="realsense_camera_depth_optical_frame"/>
      
    <!-- camera left IR joints and links -->
    <joint name="realsense_camera_left_ir_joint" type="fixed">
      <origin xyz="0 ${d435_cam_depth_to_left_ir_offset} 0" rpy="0 0 0" />
      <parent link="realsense_camera_depth_frame" />
      <child link="realsense_camera_left_ir_frame" />
    </joint>
    <link name="realsense_camera_left_ir_frame"/>

    <joint name="realsense_camera_left_ir_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="realsense_camera_left_ir_frame" />
      <child link="realsense_camera_left_ir_optical_frame" />
    </joint>
    <link name="realsense_camera_left_ir_optical_frame"/>

    <!-- camera right IR joints and links -->
    <joint name="realsense_camera_right_ir_joint" type="fixed">
      <origin xyz="0 ${d435_cam_depth_to_right_ir_offset} 0" rpy="0 0 0" />
      <parent link="realsense_camera_depth_frame" />
      <child link="realsense_camera_right_ir_frame" />
    </joint>
    <link name="realsense_camera_right_ir_frame"/>

    <joint name="realsense_camera_right_ir_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="realsense_camera_right_ir_frame" />
      <child link="realsense_camera_right_ir_optical_frame" />
    </joint>
    <link name="realsense_camera_right_ir_optical_frame"/>

    <!-- camera color joints and links -->
    <joint name="realsense_camera_color_joint" type="fixed">
      <origin xyz="0 ${d435_cam_depth_to_color_offset} 0" rpy="0 0 0" />
      <parent link="realsense_camera_depth_frame" />
      <child link="realsense_camera_color_frame" />
    </joint>
    <link name="realsense_camera_color_frame"/>

    <joint name="realsense_camera_color_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="realsense_camera_color_frame" />
      <child link="realsense_camera_color_optical_frame" />
    </joint>
    <link name="realsense_camera_color_optical_frame"/>

    <!-- Load parameters to model's main link-->

  <gazebo reference="realsense_camera_link">
      <sensor type="camera" name="realsense_camera">
          <update_rate>30.0</update_rate>
          <camera name="head">
              <horizontal_fov>1.3962634</horizontal_fov>
              <image>
                  <width>800</width>
                  <height>600</height>
                  <format>R8G8B8</format>
              </image>
              <clip>
                  <near>0.02</near>
                  <far>300</far>
              </clip>
              <noise>
                  <type>gaussian</type>
                  <mean>0.0</mean>
                  <stddev>0.007</stddev>
              </noise>
          </camera>
          <plugin name="realsense_camera_controller" filename="libgazebo_ros_camera.so">
              <alwaysOn>true</alwaysOn>
              <updateRate>30.0</updateRate>
              <cameraName>realsense/camera</cameraName>
              <imageTopicName>realsense/image_raw</imageTopicName>
              <cameraInfoTopicName>realsense_camera_info</cameraInfoTopicName>
              <frameName>realsense_camera_link</frameName>
              <hackBaseline>0.07</hackBaseline>
              <distortionK1>0.0</distortionK1>
              <distortionK2>0.0</distortionK2>
              <distortionK3>0.0</distortionK3>
              <distortionT1>0.0</distortionT1>
              <distortionT2>0.0</distortionT2>
          </plugin>
      </sensor>
  </gazebo>

    <gazebo reference="realsense_camera_link">
      <sensor name="intel_realsense_r200_depth" type="depth">
        <always_on>1</always_on>
        <update_rate>1</update_rate>
        <pose>0.064 -0.047 0.107 0 0 0</pose>
        <camera name="realsense_depth_camera">
        </camera>
	      <plugin name="intel_realsense_r200_depth_driver" filename="libgazebo_ros_camera.so">
            <ros>
        <!-- 
              <argument>custom_camera/image_raw:=custom_camera/custom_image</argument>
              <argument>custom_camera/image_depth:=custom_camera/custom_image_depth</argument>
              <argument>custom_camera/camera_info:=custom_camera/custom_info_raw</argument>
              <argument>custom_camera/camera_info_depth:=custom_camera/custom_info_depth</argument>
              <argument>custom_camera/points:=custom_camera/custom_points</argument> 
        -->
            </ros>
            <camera_name>intel_realsense_r200_depth</camera_name>
            <frame_name>realsense_camera_depth_optical_frame</frame_name>
            <hack_baseline>0.07</hack_baseline>
            <min_depth>0.001</min_depth>
          </plugin>
      </sensor>

  </gazebo>

</robot>
